package commands.admin

import net.dv8tion.jda.api.EmbedBuilder
import net.dv8tion.jda.api.Permission
import net.dv8tion.jda.api.entities.Member
import net.dv8tion.jda.api.entities.UserSnowflake
import net.dv8tion.jda.api.events.interaction.command.SlashCommandInteractionEvent
import net.dv8tion.jda.api.hooks.ListenerAdapter
import net.dv8tion.jda.api.interactions.commands.OptionMapping
import org.fusesource.jansi.Ansi.ansi
import org.fusesource.jansi.AnsiConsole
import utils.NekoCLIApi
import java.awt.Color
import java.time.Duration
import java.time.Instant
import java.time.ZoneId
import java.time.format.DateTimeFormatter
import kotlin.random.Random

class Ban : ListenerAdapter() {

    private val api = NekoCLIApi()
    private val funnyPhrases = listOf(
        "Oops, you got banned!",
        "Enjoy your permanent vacation!",
        "Adios, muchacho!",
        "You're outta here!",
        "Buh-bye!",
        "Bye-bye, Felicia!",
        "Sayonara, sucker!",
        "Another one bites the dust!",
        "You've been evicted from the server!",
        "Don't let the door hit you on the way out!",
        "Don't let the door hit you on the way out!",
        "Hasta la vista, baby!",
        "Hasta la vista, baby!",
        "Don't let the door hit you on the way out!",
        "Goodbye and good riddance!",
        "You've been evicted from the server!",
        "Better luck next time!",
        "Hasta la vista, baby!",
        "Oops, you got banned!",
        "Goodbye and good riddance!",
        "Enjoy your permanent vacation!",
        "Goodnight, sweet prince!",
        "You've been yeeted!",
        "You're outta here!",
        "Hasta luego, amigo!",
        "Enjoy your permanent vacation!",
        "So long, partner!",
        "You've been evicted from the server!",
        "Adios, muchacho!",
        "You've been evicted from the server!",
        "Oops, you got banned!",
        "You've been evicted from the server!",
        "Bye-bye, Felicia!",
        "Oops, you got banned!",
        "You're outta here!",
        "Goodbye and good riddance!",
        "You've been evicted from the server!",
        "Another one bites the dust!",
        "You've been yeeted!",
        "The ban hammer has spoken!",
        "Hasta la vista, baby!",
        "The ban hammer has spoken!",
        "Adios, muchacho!",
        "The ban hammer has spoken!",
        "Buh-bye!",
        "The ban hammer has spoken!",
        "Goodnight, sweet prince!",
        "Enjoy your permanent vacation!",
        "Goodnight, sweet prince!",
        "Don't let the door hit you on the way out!",
        "Sayonara, sucker!",
        "Adios, muchacho!",
        "See you never!",
        "You've been yeeted!",
        "You've been yeeted!",
        "Better luck next time!",
        "Bye-bye, Felicia!",
        "Enjoy your permanent vacation!",
        "Enjoy your permanent vacation!",
        "Poof! You're gone!",
        "The ban hammer has spoken!",
        "You've been evicted from the server!",
        "You've been evicted from the server!",
        "You've been yeeted!",
        "You're outta here!",
        "You've been yeeted!",
        "Sayonara, sucker!",
        "Oops, you got banned!",
        "Bye-bye, Felicia!",
        "Buh-bye!",
        "Hasta la vista, baby!",
        "Hasta la vista, baby!",
        "So long, partner!",
        "Oops, you got banned!",
        "You're outta here!",
        "You've been yeeted!",
        "Bye-bye, Felicia!",
        "Goodnight, sweet prince!",
        "Oops, you got banned!",
        "Goodbye and good riddance!",
        "Hasta luego, amigo!",
        "Better luck next time!",
        "See you never!",
        "Another one bites the dust!",
        "You've been yeeted!",
        "The ban hammer has spoken!",
        "Poof! You're gone!",
        "Better luck next time!",
        "Goodbye and good riddance!",
        "Poof! You're gone!",
        "Hasta luego, amigo!",
        "You've been evicted from the server!",
        "Enjoy your permanent vacation!",
        "Enjoy your permanent vacation!",
        "Don't let the door hit you on the way out!",
        "Bye-bye, Felicia!",
        "Adios, muchacho!",
        "You've been evicted from the server!",
        "So long, partner!",
        "You've been yeeted!",
        "Buh-bye!",
        "Buh-bye!",
        "So long, partner!",
        "Goodbye and good riddance!",
        "Buh-bye!",
        "You've been yeeted!",
        "Poof! You're gone!",
        "Enjoy your permanent vacation!",
        "Sayonara, sucker!",
        "Bye-bye, Felicia!",
        "The ban hammer has spoken!",
        "Hasta la vista, baby!",
        "Better luck next time!",
        "Don't let the door hit you on the way out!",
        "You've been evicted from the server!",
        "Bye-bye, Felicia!",
        "Hasta la vista, baby!",
        "You're outta here!",
        "Better luck next time!",
        "So long, partner!",
        "Goodbye and good riddance!",
        "Another one bites the dust!",
        "Better luck next time!",
        "You're outta here!",
        "Hasta la vista, baby!",
        "Sayonara, sucker!",
        "Don't let the door hit you on the way out!",
        "So long, partner!",
        "You've been evicted from the server!",
        "Oops, you got banned!",
        "Don't let the door hit you on the way out!",
        "Better luck next time!",
        "You've been evicted from the server!",
        "Enjoy your permanent vacation!",
        "Goodnight, sweet prince!",
        "You're outta here!",
        "Goodbye and good riddance!",
        "Better luck next time!",
        "Oops, you got banned!",
        "Adios, muchacho!",
        "Hasta la vista, baby!",
        "Better luck next time!",
        "Better luck next time!",
        "Goodbye and good riddance!",
        "Another one bites the dust!",
        "Buh-bye!",
        "Adios, muchacho!",
        "Hasta luego, amigo!",
        "Sayonara, sucker!",
        "Adios, muchacho!",
        "Hasta luego, amigo!",
        "You're outta here!",
        "Adios, muchacho!",
        "Enjoy your permanent vacation!",
        "Another one bites the dust!",
        "Sayonara, sucker!",
        "Hasta la vista, baby!",
        "Goodnight, sweet prince!",
        "Another one bites the dust!",
        "Goodbye and good riddance!",
        "Better luck next time!",
        "See you never!",
        "Goodnight, sweet prince!",
        "Adios, muchacho!",
        "Hasta luego, amigo!",
        "Bye-bye, Felicia!",
        "Buh-bye!",
        "You're outta here!",
        "Hasta la vista, baby!",
        "So long, partner!",
        "The ban hammer has spoken!",
        "You've been evicted from the server!",
        "See you never!",
        "Bye-bye, Felicia!",
        "Another one bites the dust!",
        "Goodnight, sweet prince!",
        "The ban hammer has spoken!",
        "Adios, muchacho!",
        "Better luck next time!",
        "You're outta here!",
        "Buh-bye!",
        "So long, partner!",
        "Goodbye and good riddance!",
        "So long, partner!",
        "The ban hammer has spoken!",
        "Better luck next time!",
        "Bye-bye, Felicia!",
        "Buh-bye!",
        "Adios, muchacho!",
        "You've been evicted from the server!",
        "Don't let the door hit you on the way out!",
        "Adios, muchacho!",
        "Enjoy your permanent vacation!",
        "You're outta here!",
        "Sayonara, sucker!",
        "You've been yeeted!",
        "Poof! You're gone!",
        "Hasta la vista, baby!",
        "So long, partner!",
        "Bye-bye, Felicia!",
        "Poof! You're gone!",
        "Enjoy your permanent vacation!",
        "Goodnight, sweet prince!",
        "Adios, muchacho!",
        "Hasta luego, amigo!",
        "Goodbye and good riddance!",
        "Adios, muchacho!",
        "Goodbye and good riddance!",
        "Better luck next time!",
        "Hasta luego, amigo!",
        "You've been yeeted!",
        "Hasta luego, amigo!",
        "Better luck next time!",
        "Adios, muchacho!",
        "You've been evicted from the server!",
        "Sayonara, sucker!",
        "The ban hammer has spoken!",
        "Another one bites the dust!",
        "Goodbye and good riddance!",
        "See you never!",
        "Another one bites the dust!",
        "Don't let the door hit you on the way out!",
        "See you never!",
        "Poof! You're gone!",
        "Buh-bye!",
        "Adios, muchacho!",
        "Goodnight, sweet prince!",
        "Buh-bye!",
        "You're outta here!",
        "Oops, you got banned!",
        "Goodbye and good riddance!",
        "Hasta la vista, baby!",
        "Poof! You're gone!",
        "So long, partner!",
        "Another one bites the dust!",
        "Adios, muchacho!",
        "You're outta here!",
        "You're outta here!",
        "You've been yeeted!",
        "Hasta la vista, baby!",
        "Bye-bye, Felicia!",
        "The ban hammer has spoken!",
        "Hasta luego, amigo!",
        "Bye-bye, Felicia!",
        "Bye-bye, Felicia!",
        "So long, partner!",
        "Sayonara, sucker!",
        "Buh-bye!",
        "Better luck next time!",
        "You've been yeeted!",
        "Goodbye and good riddance!",
        "Goodbye and good riddance!",
        "Oops, you got banned!",
        "Sayonara, sucker!",
        "Hasta la vista, baby!",
        "Hasta luego, amigo!",
        "You're outta here!",
        "Don't let the door hit you on the way out!",
        "Oops, you got banned!",
        "Better luck next time!",
        "Better luck next time!",
        "You're outta here!",
        "Another one bites the dust!",
        "Enjoy your permanent vacation!",
        "Hasta luego, amigo!",
        "Hasta luego, amigo!",
        "Bye-bye, Felicia!",
        "Adios, muchacho!",
        "You're outta here!",
        "Don't let the door hit you on the way out!",
        "Poof! You're gone!",
        "Bye-bye, Felicia!",
        "So long, partner!",
        "Enjoy your permanent vacation!",
        "Better luck next time!",
        "See you never!",
        "The ban hammer has spoken!",
        "Oops, you got banned!",
        "Hasta luego, amigo!",
        "Bye-bye, Felicia!",
        "Better luck next time!",
        "Bye-bye, Felicia!",
        "Better luck next time!",
        "Better luck next time!",
        "Another one bites the dust!",
        "Sayonara, sucker!",
        "Another one bites the dust!",
        "You've been evicted from the server!",
        "The ban hammer has spoken!",
        "Hasta la vista, baby!",
        "Bye-bye, Felicia!",
        "Bye-bye, Felicia!",
        "Oops, you got banned!",
        "Goodnight, sweet prince!",
        "Buh-bye!",
        "You're outta here!",
        "Hasta luego, amigo!",
        "See you never!",
        "Don't let the door hit you on the way out!",
        "The ban hammer has spoken!",
        "Better luck next time!",
        "Bye-bye, Felicia!",
        "So long, partner!",
        "Buh-bye!",
        "Don't let the door hit you on the way out!",
        "Better luck next time!",
        "Better luck next time!",
        "The ban hammer has spoken!",
        "Buh-bye!",
        "Adios, muchacho!",
        "So long, partner!",
        "You're outta here!",
        "Another one bites the dust!",
        "Goodnight, sweet prince!",
        "Oops, you got banned!",
        "You're outta here!",
        "The ban hammer has spoken!",
        "Goodbye and good riddance!",
        "Goodbye and good riddance!",
        "Hasta luego, amigo!",
        "You're outta here!",
        "Bye-bye, Felicia!",
        "See you never!",
        "Goodbye and good riddance!",
        "Better luck next time!",
        "You're outta here!",
        "Poof! You're gone!",
        "Goodbye and good riddance!",
        "Buh-bye!",
        "Another one bites the dust!",
        "Poof! You're gone!",
        "You've been yeeted!",
        "You're outta here!",
        "Goodbye and good riddance!",
        "Bye-bye, Felicia!",
        "Buh-bye!",
        "Another one bites the dust!",
        "Goodbye and good riddance!",
        "So long, partner!",
        "So long, partner!",
        "You've been evicted from the server!",
        "Buh-bye!",
        "Poof! You're gone!",
        "Goodbye and good riddance!",
        "You've been evicted from the server!",
        "The ban hammer has spoken!",
        "So long, partner!",
        "Sayonara, sucker!",
        "The ban hammer has spoken!",
        "Buh-bye!",
        "Enjoy your permanent vacation!",
        "See you never!",
        "You've been evicted from the server!",
        "Sayonara, sucker!",
        "Poof! You're gone!",
        "Another one bites the dust!",
        "You've been evicted from the server!",
        "Hasta luego, amigo!",
        "You've been evicted from the server!",
        "See you never!",
        "You've been yeeted!",
        "Adios, muchacho!",
        "Hasta la vista, baby!",
        "Adios, muchacho!",
        "Oops, you got banned!",
        "The ban hammer has spoken!",
        "See you never!",
        "So long, partner!",
        "Better luck next time!",
        "Better luck next time!",
        "Oops, you got banned!",
        "Goodbye and good riddance!",
        "You've been evicted from the server!",
        "So long, partner!",
        "Better luck next time!",
        "You've been evicted from the server!",
        "Enjoy your permanent vacation!",
        "Buh-bye!",
        "Another one bites the dust!",
        "Hasta luego, amigo!",
        "So long, partner!",
        "Goodnight, sweet prince!",
        "Bye-bye, Felicia!",
        "Hasta la vista, baby!",
        "Goodbye and good riddance!",
        "Goodnight, sweet prince!",
        "Adios, muchacho!",
        "Enjoy your permanent vacation!",
        "So long, partner!",
        "Another one bites the dust!",
        "Hasta luego, amigo!",
        "Poof! You're gone!",
        "Better luck next time!",
        "So long, partner!",
        "You've been evicted from the server!",
        "See you never!",
        "So long, partner!",
        "Adios, muchacho!",
        "So long, partner!",
        "Oops, you got banned!",
        "Goodnight, sweet prince!",
        "The ban hammer has spoken!",
        "The ban hammer has spoken!",
        "You've been evicted from the server!",
        "Poof! You're gone!",
        "The ban hammer has spoken!",
        "You've been yeeted!",
        "Sayonara, sucker!",
        "See you never!",
        "You've been evicted from the server!",
        "So long, partner!",
        "Goodbye and good riddance!",
        "Goodbye and good riddance!",
        "Hasta luego, amigo!",
        "Sayonara, sucker!",
        "Oops, you got banned!",
        "Goodnight, sweet prince!",
        "You've been evicted from the server!",
        "Poof! You're gone!",
        "Goodbye and good riddance!",
        "You've been evicted from the server!",
        "Adios, muchacho!",
        "You've been yeeted!",
        "You're outta here!",
        "Goodbye and good riddance!",
        "Hasta luego, amigo!",
        "Bye-bye, Felicia!",
        "Goodnight, sweet prince!",
        "So long, partner!",
        "Adios, muchacho!",
        "So long, partner!",
        "Enjoy your permanent vacation!",
        "The ban hammer has spoken!",
        "Goodnight, sweet prince!",
        "Buh-bye!",
        "Enjoy your permanent vacation!",
        "You're outta here!",
        "Bye-bye, Felicia!",
        "Goodbye and good riddance!",
        "The ban hammer has spoken!",
        "Sayonara, sucker!",
        "Goodnight, sweet prince!",
        "Enjoy your permanent vacation!",
        "Enjoy your permanent vacation!",
        "Adios, muchacho!",
        "See you never!",
        "Bye-bye, Felicia!",
        "Better luck next time!",
        "Bye-bye, Felicia!",
        "You've been yeeted!",
        "Sayonara, sucker!",
        "The ban hammer has spoken!",
        "You've been evicted from the server!",
        "Goodnight, sweet prince!",
        "You're outta here!",
        "You're outta here!",
        "Hasta la vista, baby!",
        "Adios, muchacho!",
        "You've been yeeted!",
        "The ban hammer has spoken!",
        "Goodnight, sweet prince!",
        "You've been yeeted!",
        "Better luck next time!",
        "See you never!",
        "Hasta la vista, baby!",
        "You've been evicted from the server!",
        "Another one bites the dust!",
        "Enjoy your permanent vacation!",
        "The ban hammer has spoken!",
        "See you never!",
        "You've been yeeted!",
        "Another one bites the dust!",
        "Poof! You're gone!",
        "You're outta here!",
        "Goodbye and good riddance!",
        "Buh-bye!",
        "You've been evicted from the server!",
        "Enjoy your permanent vacation!",
        "Buh-bye!",
        "Hasta la vista, baby!",
        "Enjoy your permanent vacation!",
        "Oops, you got banned!",
        "Bye-bye, Felicia!",
        "So long, partner!",
        "Adios, muchacho!",
        "Goodbye and good riddance!",
        "Oops, you got banned!",
        "Sayonara, sucker!",
        "Oops, you got banned!",
        "You've been yeeted!",
        "You've been evicted from the server!",
        "So long, partner!",
        "Another one bites the dust!",
        "Don't let the door hit you on the way out!",
        "You're outta here!",
        "Hasta la vista, baby!",
        "Bye-bye, Felicia!",
        "You've been evicted from the server!",
        "So long, partner!",
        "Hasta la vista, baby!",
        "Enjoy your permanent vacation!",
        "You're outta here!",
        "Poof! You're gone!",
        "Poof! You're gone!",
        "Adios, muchacho!",
        "Buh-bye!",
        "Goodbye and good riddance!",
        "Bye-bye, Felicia!",
        "The ban hammer has spoken!",
        "Hasta luego, amigo!",
        "Poof! You're gone!",
        "Goodnight, sweet prince!",
        "Enjoy your permanent vacation!",
        "Another one bites the dust!",
        "So long, partner!",
        "Better luck next time!",
        "The ban hammer has spoken!",
        "Oops, you got banned!",
        "Bye-bye, Felicia!",
        "You're outta here!",
        "Poof! You're gone!",
        "Bye-bye, Felicia!",
        "You've been yeeted!",
        "See you never!",
        "Adios, muchacho!",
        "Buh-bye!",
        "Buh-bye!",
        "Hasta la vista, baby!",
        "Oops, you got banned!",
        "Oops, you got banned!",
        "Don't let the door hit you on the way out!",
        "So long, partner!",
        "Don't let the door hit you on the way out!",
        "See you never!",
        "Adios, muchacho!",
        "Hasta luego, amigo!",
        "Enjoy your permanent vacation!",
        "Oops, you got banned!",
        "See you never!",
        "Enjoy your permanent vacation!",
        "Sayonara, sucker!",
        "Oops, you got banned!",
        "Goodnight, sweet prince!",
        "Another one bites the dust!",
        "Goodbye and good riddance!",
        "See you never!",
        "Sayonara, sucker!",
        "Adios, muchacho!",
        "Hasta la vista, baby!",
        "Buh-bye!",
        "You've been evicted from the server!",
        "Better luck next time!",
        "Hasta la vista, baby!",
        "Hasta la vista, baby!",
        "Buh-bye!",
        "Sayonara, sucker!",
        "Another one bites the dust!",
        "Poof! You're gone!",
        "Poof! You're gone!",
        "Adios, muchacho!",
        "The ban hammer has spoken!",
        "Oops, you got banned!",
        "Buh-bye!",
        "Enjoy your permanent vacation!",
        "Don't let the door hit you on the way out!",
        "Poof! You're gone!",
        "You've been yeeted!",
        "You've been yeeted!",
        "You've been evicted from the server!",
        "Enjoy your permanent vacation!",
        "Better luck next time!",
        "Oops, you got banned!",
        "Goodnight, sweet prince!",
        "You've been evicted from the server!",
        "You've been evicted from the server!",
        "Buh-bye!",
        "Bye-bye, Felicia!",
        "Oops, you got banned!",
        "Hasta la vista, baby!",
        "Better luck next time!",
        "Better luck next time!",
        "Better luck next time!",
        "Goodbye and good riddance!",
        "Buh-bye!",
        "You're outta here!",
        "You're outta here!",
        "Oops, you got banned!",
        "Hasta luego, amigo!",
        "Bye-bye, Felicia!",
        "Oops, you got banned!",
        "Adios, muchacho!",
        "You've been yeeted!",
        "Hasta luego, amigo!",
        "See you never!",
        "Oops, you got banned!",
        "Hasta luego, amigo!",
        "Better luck next time!",
        "You've been yeeted!",
        "Hasta la vista, baby!",
        "The ban hammer has spoken!",
        "The ban hammer has spoken!",
        "Don't let the door hit you on the way out!",
        "See you never!",
        "Another one bites the dust!",
        "Goodbye and good riddance!",
        "Goodbye and good riddance!",
        "So long, partner!",
        "Bye-bye, Felicia!",
        "Don't let the door hit you on the way out!",
        "Better luck next time!",
        "Oops, you got banned!",
        "The ban hammer has spoken!",
        "Better luck next time!",
        "Sayonara, sucker!",
        "Another one bites the dust!",
        "You're outta here!",
        "Buh-bye!",
        "Don't let the door hit you on the way out!",
        "Hasta la vista, baby!",
        "You've been evicted from the server!",
        "You've been evicted from the server!",
        "Hasta luego, amigo!",
        "Enjoy your permanent vacation!",
        "The ban hammer has spoken!",
        "Adios, muchacho!",
        "You're outta here!",
        "Don't let the door hit you on the way out!",
        "The ban hammer has spoken!",
        "You've been evicted from the server!",
        "Poof! You're gone!",
        "Don't let the door hit you on the way out!",
        "You're outta here!",
        "See you never!",
        "See you never!",
        "Hasta la vista, baby!",
        "Hasta la vista, baby!",
        "Poof! You're gone!",
        "So long, partner!",
        "Another one bites the dust!",
        "Oops, you got banned!",
        "So long, partner!",
        "Hasta luego, amigo!",
        "Bye-bye, Felicia!",
        "Don't let the door hit you on the way out!",
        "Buh-bye!",
        "So long, partner!",
        "Sayonara, sucker!",
        "Poof! You're gone!",
        "The ban hammer has spoken!",
        "Sayonara, sucker!",
        "You've been evicted from the server!",
        "You've been evicted from the server!",
        "You've been yeeted!",
        "You've been evicted from the server!",
        "Hasta luego, amigo!",
        "Hasta la vista, baby!",
        "So long, partner!",
        "Sayonara, sucker!",
        "Hasta luego, amigo!",
        "Hasta la vista, baby!",
        "Enjoy your permanent vacation!",
        "Poof! You're gone!",
        "Oops, you got banned!",
        "Buh-bye!",
        "Another one bites the dust!",
        "You're outta here!",
        "You've been yeeted!",
        "Poof! You're gone!",
        "Oops, you got banned!",
        "Better luck next time!",
        "So long, partner!",
        "Bye-bye, Felicia!",
        "You've been yeeted!",
        "See you never!",
        "Bye-bye, Felicia!",
        "Poof! You're gone!",
        "Don't let the door hit you on the way out!",
        "Goodbye and good riddance!",
        "You've been evicted from the server!",
        "Don't let the door hit you on the way out!",
        "Sayonara, sucker!",
        "Oops, you got banned!",
        "So long, partner!",
        "You've been evicted from the server!",
        "You've been evicted from the server!",
        "You've been evicted from the server!",
        "You've been yeeted!",
        "Don't let the door hit you on the way out!",
        "So long, partner!",
        "Goodnight, sweet prince!",
        "Another one bites the dust!",
        "Enjoy your permanent vacation!",
        "Buh-bye!",
        "Better luck next time!",
        "Buh-bye!",
        "Oops, you got banned!",
        "Oops, you got banned!",
        "Hasta luego, amigo!",
        "So long, partner!",
        "You've been evicted from the server!",
        "The ban hammer has spoken!",
        "Hasta la vista, baby!",
        "Better luck next time!",
        "You've been evicted from the server!",
        "Enjoy your permanent vacation!",
        "Enjoy your permanent vacation!",
        "Don't let the door hit you on the way out!",
        "The ban hammer has spoken!",
        "Buh-bye!",
        "Another one bites the dust!",
        "Hasta luego, amigo!",
        "Poof! You're gone!",
        "Better luck next time!",
        "Sayonara, sucker!",
        "Hasta luego, amigo!",
        "Goodnight, sweet prince!",
        "Buh-bye!",
        "Enjoy your permanent vacation!",
        "Enjoy your permanent vacation!",
        "You've been evicted from the server!",
        "Better luck next time!",
        "Don't let the door hit you on the way out!",
        "Goodnight, sweet prince!",
        "Don't let the door hit you on the way out!",
        "Poof! You're gone!",
        "Hasta la vista, baby!",
        "Buh-bye!",
        "Don't let the door hit you on the way out!",
        "Goodnight, sweet prince!",
        "Adios, muchacho!",
        "Another one bites the dust!",
        "You've been yeeted!",
        "See you never!",
        "Hasta luego, amigo!",
        "Poof! You're gone!",
        "Adios, muchacho!",
        "Oops, you got banned!",
        "Don't let the door hit you on the way out!",
        "Better luck next time!",
        "Better luck next time!",
        "Goodbye and good riddance!",
        "See you never!",
        "The ban hammer has spoken!",
        "Another one bites the dust!",
        "The ban hammer has spoken!",
        "You've been evicted from the server!",
        "Oops, you got banned!",
        "The ban hammer has spoken!",
        "See you never!",
        "Oops, you got banned!",
        "Don't let the door hit you on the way out!",
        "The ban hammer has spoken!",
        "Hasta la vista, baby!",
        "Poof! You're gone!",
        "Goodnight, sweet prince!",
        "Buh-bye!",
        "Hasta la vista, baby!",
        "You've been yeeted!",
        "You've been yeeted!",
        "See you never!",
        "Bye-bye, Felicia!",
        "Bye-bye, Felicia!",
        "Hasta luego, amigo!",
        "See you never!",
        "Hasta luego, amigo!",
        "The ban hammer has spoken!",
        "Better luck next time!",
        "You're outta here!",
        "Bye-bye, Felicia!",
        "Better luck next time!",
        "Sayonara, sucker!",
        "Goodnight, sweet prince!",
        "Oops, you got banned!",
        "Hasta luego, amigo!",
        "You've been evicted from the server!",
        "The ban hammer has spoken!",
        "Another one bites the dust!",
        "Goodnight, sweet prince!",
        "So long, partner!",
        "The ban hammer has spoken!",
        "Goodnight, sweet prince!",
        "Hasta la vista, baby!",
        "You've been evicted from the server!",
        "Oops, you got banned!",
        "The ban hammer has spoken!",
        "You're outta here!",
        "You're outta here!",
        "Bye-bye, Felicia!",
        "Poof! You're gone!",
        "So long, partner!",
        "Another one bites the dust!",
        "Another one bites the dust!",
        "The ban hammer has spoken!",
        "So long, partner!",
        "So long, partner!",
        "Better luck next time!",
        "Adios, muchacho!",
        "Adios, muchacho!",
        "You've been yeeted!",
        "Hasta luego, amigo!",
        "Bye-bye, Felicia!",
        "You've been evicted from the server!",
        "You've been yeeted!",
        "Oops, you got banned!",
        "Oops, you got banned!",
        "Goodnight, sweet prince!",
        "Don't let the door hit you on the way out!",
        "Don't let the door hit you on the way out!",
        "Don't let the door hit you on the way out!",
        "Sayonara, sucker!",
        "Don't let the door hit you on the way out!",
        "Oops, you got banned!",
        "See you never!",
        "Buh-bye!",
        "You're outta here!",
        "Hasta luego, amigo!",
        "The ban hammer has spoken!",
        "So long, partner!",
        "Hasta luego, amigo!",
        "Adios, muchacho!",
        "Enjoy your permanent vacation!",
        "Goodbye and good riddance!",
        "Poof! You're gone!",
        "Goodnight, sweet prince!",
        "Enjoy your permanent vacation!",
        "So long, partner!",
        "Sayonara, sucker!",
        "See you never!",
        "Another one bites the dust!",
        "Goodnight, sweet prince!",
        "Buh-bye!",
        "Oops, you got banned!",
        "Sayonara, sucker!",
        "Buh-bye!",
        "You've been evicted from the server!",
        "You've been yeeted!",
        "Adios, muchacho!",
        "Goodbye and good riddance!",
        "Hasta la vista, baby!",
        "Adios, muchacho!",
        "So long, partner!",
        "Hasta luego, amigo!",
        "Goodnight, sweet prince!",
        "You've been yeeted!",
        "See you never!",
        "Bye-bye, Felicia!",
        "Sayonara, sucker!",
        "Enjoy your permanent vacation!",
        "Buh-bye!",
        "Sayonara, sucker!",
        "You've been yeeted!",
        "You're outta here!",
        "So long, partner!",
        "Poof! You're gone!",
        "Poof! You're gone!",
        "Another one bites the dust!",
        "You've been yeeted!",
        "You're outta here!",
        "Oops, you got banned!",
        "Goodnight, sweet prince!",
        "Hasta luego, amigo!",
        "Better luck next time!",
        "Adios, muchacho!",
        "Enjoy your permanent vacation!",
        "Bye-bye, Felicia!",
        "Better luck next time!",
        "You've been evicted from the server!",
        "Oops, you got banned!",
        "Oops, you got banned!",
        "Poof! You're gone!",
        "So long, partner!",
        "Hasta luego, amigo!",
        "Enjoy your permanent vacation!",
        "Hasta la vista, baby!",
        "Oops, you got banned!",
        "Goodnight, sweet prince!",
        "You're outta here!",
        "You've been evicted from the server!",
        "Don't let the door hit you on the way out!",
        "Sayonara, sucker!",
        "You've been yeeted!",
        "So long, partner!",
        "Enjoy your permanent vacation!",
        "The ban hammer has spoken!",
        "Sayonara, sucker!",
        "Sayonara, sucker!",
        "You've been evicted from the server!",
        "Enjoy your permanent vacation!",
        "Adios, muchacho!",
        "Buh-bye!",
        "Buh-bye!",
        "Buh-bye!",
        "Another one bites the dust!",
        "Goodbye and good riddance!",
        "Don't let the door hit you on the way out!",
        "Oops, you got banned!",
        "Oops, you got banned!",
        "Enjoy your permanent vacation!",
        "Better luck next time!",
        "Hasta la vista, baby!",
        "You're outta here!",
        "Buh-bye!",
        "Goodbye and good riddance!",
        "Another one bites the dust!",
        "Enjoy your permanent vacation!",
        "So long, partner!",
        "Goodbye and good riddance!",
        "The ban hammer has spoken!",
        "Oops, you got banned!",
        "You've been evicted from the server!",
        "Oops, you got banned!",
        "Hasta luego, amigo!",
        "So long, partner!",
        "Hasta la vista, baby!",
        "Buh-bye!",
        "You're outta here!",
        "You're outta here!",
        "Hasta luego, amigo!",
        "So long, partner!",
        "You've been yeeted!",
        "Oops, you got banned!",
        "Hasta luego, amigo!",
        "Hasta luego, amigo!",
        "Adios, muchacho!",
        "Hasta la vista, baby!",
        "You've been yeeted!",
        "Better luck next time!",
        "Better luck next time!",
        "You're outta here!",
        "Bye-bye, Felicia!",
        "Poof! You're gone!",
        "Hasta la vista, baby!",
        "So long, partner!",
        "Goodnight, sweet prince!",
        "Poof! You're gone!",
        "The ban hammer has spoken!",
        "Oops, you got banned!",
        "Better luck next time!",
        "Goodbye and good riddance!",
        "See you never!",
        "Goodbye and good riddance!",
        "Enjoy your permanent vacation!",
        "Goodnight, sweet prince!",
        "Bye-bye, Felicia!",
        "Better luck next time!",
        "You've been evicted from the server!",
        "Goodnight, sweet prince!",
        "Hasta luego, amigo!",
        "Hasta la vista, baby!",
        "Better luck next time!",
        "Goodbye and good riddance!",
        "Enjoy your permanent vacation!",
        "Enjoy your permanent vacation!",
        "Enjoy your permanent vacation!",
        "Better luck next time!",
        "Goodnight, sweet prince!",
        "So long, partner!",
        "Hasta luego, amigo!",
        "Poof! You're gone!",
        "Buh-bye!",
        "Hasta luego, amigo!",
        "Don't let the door hit you on the way out!",
        "Sayonara, sucker!",
        "Goodbye and good riddance!",
        "Goodnight, sweet prince!",
        "Better luck next time!",
        "Adios, muchacho!",
        "You've been evicted from the server!",
        "You've been yeeted!",
        "The ban hammer has spoken!",
        "Goodbye and good riddance!",
        "You're outta here!",
        "Enjoy your permanent vacation!",
        "Bye-bye, Felicia!",
        "Poof! You're gone!",
        "Hasta la vista, baby!",
        "You've been evicted from the server!",
        "You've been yeeted!",
        "Goodbye and good riddance!",
        "You're outta here!",
        "Goodbye and good riddance!",
        "Hasta luego, amigo!",
        "Bye-bye, Felicia!",
        "You're outta here!",
        "Goodnight, sweet prince!",
        "You're outta here!",
        "You're outta here!",
        "Goodnight, sweet prince!",
        "Another one bites the dust!",
        "Enjoy your permanent vacation!",
        "Hasta luego, amigo!",
        "Hasta luego, amigo!",
        "Don't let the door hit you on the way out!",
        "Goodnight, sweet prince!",
        "See you never!",
        "Goodnight, sweet prince!",
        "Another one bites the dust!",
        "Buh-bye!",
        "Buh-bye!",
        "Adios, muchacho!"
        )

    override fun onSlashCommandInteraction(event: SlashCommandInteractionEvent) {
        if (event.name != "ban") return

        val guild = event.guild
        if (guild == null || guild.id != api.getConfig("GUILDID")) {
            event.replyEmbeds(
                EmbedBuilder()
                    .setTitle("❌ Access Denied")
                    .setDescription("You are not in the correct server to use this command.")
                    .setColor(Color.RED)
                    .setAuthor(event.jda.selfUser.name, api.getConfig("WEBSITE"), event.jda.selfUser.avatarUrl)
                    .setTimestamp(event.timeCreated)
                    .build()
            ).setEphemeral(true).queue()
            return
        }

        val member = event.member
        if (member == null || !member.hasPermission(Permission.BAN_MEMBERS)) {
            event.replyEmbeds(
                EmbedBuilder()
                    .setTitle("❌ Insufficient Permissions")
                    .setDescription("You do not have permission to ban members.")
                    .setColor(Color.RED)
                    .setAuthor(event.jda.selfUser.name, api.getConfig("WEBSITE"), event.jda.selfUser.avatarUrl)
                    .setTimestamp(event.timeCreated)
                    .build()
            ).setEphemeral(true).queue()
            return
        }

        val target: Member? = event.getOption("user", OptionMapping::getAsMember)
        if (target == null) {
            event.replyEmbeds(
                EmbedBuilder()
                    .setTitle("❌ Invalid Target")
                    .setDescription("You must specify a valid member to ban.")
                    .setColor(Color.RED)
                    .setAuthor(event.jda.selfUser.name, api.getConfig("WEBSITE"), event.jda.selfUser.avatarUrl)
                    .setTimestamp(event.timeCreated)
                    .build()
            ).setEphemeral(true).queue()
            return
        }

        if (!member.canInteract(target)) {
            event.replyEmbeds(
                EmbedBuilder()
                    .setTitle("❌ Cannot Ban Target")
                    .setDescription("You cannot ban this user due to role hierarchy or insufficient permissions.")
                    .setColor(Color.RED)
                    .setAuthor(event.jda.selfUser.name, api.getConfig("WEBSITE"), event.jda.selfUser.avatarUrl)
                    .setTimestamp(event.timeCreated)
                    .build()
            ).setEphemeral(true).queue()
            return
        }

        val reason = event.getOption("reason", OptionMapping::getAsString) ?: "No reason provided"
        val randomPhrase = funnyPhrases[Random.nextInt(funnyPhrases.size)]
        val timestamp = Instant.now().atZone(ZoneId.systemDefault()).format(DateTimeFormatter.ofPattern("dd/MM/yyyy - HH:mm"))

        event.deferReply().queue()

        guild.ban(listOf(UserSnowflake.fromId(target.id)), Duration.ZERO)
            .reason(reason)
            .queue({
                event.hook.editOriginalEmbeds(
                    EmbedBuilder()
                        .setTitle("✅ Success")
                        .setDescription("Successfully banned ${target.user.name}.")
                        .setColor(Color.decode(api.getConfig("WORKERCOLOR")))
                        .setAuthor(event.jda.selfUser.name, api.getConfig("WEBSITE"), event.jda.selfUser.avatarUrl)
                        .addField("Reason", reason, false)
                        .addField("Banned By", event.user.name, true)
                        .addField("Timestamp", timestamp, true)
                        .addField("Message", randomPhrase, false)
                        .setTimestamp(event.timeCreated)
                        .build()
                ).queue()

                AnsiConsole.systemInstall()
                println(
                    ansi().fgBrightBlue().a("[").reset().a("NekoCLIWorker").fgBrightBlue().a("]").reset()
                        .fgBrightBlue().a(" Successfully banned ${target.user.name} ").reset()
                        .a("By: ${event.user.name}").reset()
                        .a(" | Reason: $reason | Timestamp: $timestamp | Message: $randomPhrase")
                )
            }) { error ->
                event.hook.editOriginalEmbeds(
                    EmbedBuilder()
                        .setTitle("❌ Error")
                        .setDescription("An error occurred while banning ${target.user.name}.")
                        .setColor(Color.RED)
                        .setAuthor(event.jda.selfUser.name, api.getConfig("WEBSITE"), event.jda.selfUser.avatarUrl)
                        .setTimestamp(event.timeCreated)
                        .build()
                ).queue()
                error.printStackTrace()
            }
    }
}
